### ISSUE TITLE
[$100] Add health check to UI project

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#194]
As discussed via Slack, for both develop and master.

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30103807 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30103807 has been updated - it has been assigned to thomaskranitsas.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment]
@ThomasKranitsas - Can you check this please?  It's not working in prod:

https://x.topcoder.com/health

And relevant logs:

```
2019-10-02T06:03:45.912966+00:00 heroku[router]: at=info method=GET path="/health" host=x.topcoder.com request_id=7efdea5a-7265-4d71-98a3-cbc103e03b21 fwd="86.205.119.1" dyno=web.1 connect=1ms service=3ms status=301 bytes=475 protocol=https
2019-10-02T06:03:46.033946+00:00 app[web.1]: Error: Can't set headers after they are sent.
2019-10-02T06:03:46.033961+00:00 app[web.1]: at SendStream.headersAlreadySent (/app/node_modules/send/index.js:402:13)
2019-10-02T06:03:46.033963+00:00 app[web.1]: at SendStream.send (/app/node_modules/send/index.js:625:10)
2019-10-02T06:03:46.033965+00:00 app[web.1]: at /app/node_modules/send/index.js:782:12
2019-10-02T06:03:46.033966+00:00 app[web.1]: at FSReqWrap.oncomplete (fs.js:153:5)
```

**Comment by ThomasKranitsas** [comment]
New PRs:
- https://github.com/topcoder-platform/topcoder-x-ui/pull/195
- https://github.com/topcoder-platform/topcoder-x-ui/pull/196

**Comment by jmgasper** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30103807<br/><br/>```This is an automated message for ghostar via Topcoder X```
