### ISSUE TITLE
Error in handleIssueClose

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#286]
We see this error quite a bit in the logs.  This shouldn't cause an exception - it should be handled formally:
```
debug: DB Issue number: 654
debug: DB Issue provider: github
debug: DB Issue repository: 221569487
debug: dbIssue is PENDING
error: Error happened in process
TypeError: Cannot read property 'id' of undefined
    at handleIssueClose (/topcoder-x-processor/services/IssueService.js:503:51)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
error:  message=Cannot read property 'id' of undefined, stack=TypeError: Cannot read property 'id' of undefined
    at handleIssueClose (/topcoder-x-processor/services/IssueService.js:503:51)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7), logged=true

```

**Comment by jmgasper** [comment]
Validated that this doesn't appear in the logs anymore.
