### ISSUE TITLE
[$150] Auth flow changes

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#344]
@afrisalyp - We're working on some auth flow changes and could use some help.  We've started work here:

https://github.com/topcoder-platform/topcoder-x-ui/pull/340

Basically, we're going to move from the "old" auth flow and HS256 token, to the "new" auth flow and RS256 token instead.

From Topcoder:

Logout and refresh are not working. Also code clean-up is required for decode and refresh logic. If possible lets use this lib - https://github.com/topcoder-platform/tc-auth-lib

The logout URL should look like:

https://accounts-auth0.topcoder-dev.com/?logout=true&retUrl=https%3A%2F%2Fx.topcoder-dev.com%2F

Topcoder provided this for reference:

https://github.com/appirio-tech/connect-app/pull/4082

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30144220 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30144220 has been updated - it has been assigned to afrisalyp.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by afrisalyp** [comment]
@jmgasper 

Should I use feature/Auth0-RS256-Token branch?

**Comment by jmgasper** [comment]
@afrisalyp - Sure, thanks.

**Comment by afrisalyp** [comment]
@jmgasper 

I got this error after started the `topcoder-x-ui` backend service. 
I've tried to use `babel`, but still the same.
Any steps that should I do to use `tc-auth-lib`?

```
/home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/@topcoder-platform/tc-auth-lib/src/connector-wrapper.js:10
export function configureConnector({connectorUrl, frameId, mockMode, mockToken}) {
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._compile (/home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/afrisalyp/topcoder/topcoder-x/topcoder-x-ui/node_modules/@topcoder-platform/tc-auth-lib/index.js:1:47)
```

**Comment by jmgasper** [comment]
@sachin-maheshwari ☝️  Any ideas?

**Comment by sachin-maheshwari** [comment]
@jmgasper some ES6 standards are making that cause. I handled this "esm" like - https://github.com/topcoder-platform/topcoder-x-ui/blob/feature/Auth0-RS256-Token/package.json#L14 . You can handle in different ways.

**Comment by jmgasper** [comment]
@afrisalyp - I deployed these changes to `https://x.topcoder-dev.com`.  I'm not seeing the logout working.  Can you double check please?

@sachin-maheshwari - Can you have a look as well and let me know what you think please?  We'll still need to update with the new login flow.

**Comment by afrisalyp** [comment]
@jmgasper 

Do you see screen like this?
It seems we need to fix some configuration in auth0.

I got this error message
> invalid_request: The "returnTo" querystring parameter "http://topcoderx.topcoder-dev.com/#!/app/main" is not defined as a valid URL in "Allowed Logout URLs". To add a new URL, please do it here: https://manage.auth0.com/#/applications/BXWXUWnilVUPdN01t2Se29Tw2ZYNGZvH/settings

![Screenshot from 2020-10-05 07-37-03](https://user-images.githubusercontent.com/8887344/95031022-b2aaa900-06dd-11eb-9118-b62be19338fa.png)

**Comment by sachin-maheshwari** [comment]
@jmgasper @afrisalyp check now. I changed in LONGIN_URL at aws end.

**Comment by sachin-maheshwari** [comment]
@jmgasper i don't think new "refresh token" changes working.

**Comment by sachin-maheshwari** [comment]
@jmgasper  also, can we use our central lib for auth (instead of https://github.com/topcoder-platform/topcoder-x-ui/tree/develop/src/front/src/app/auth). Example-  https://github.com/appirio-tech/connect-app/blob/test/auth0lib/package.json#L153  https://github.com/appirio-tech/connect-app/pull/4082

**Comment by jmgasper** [comment]
@sachin-maheshwari - Login URL change looks to be working.  I'm going to create new tickets for the refresh token and central lib stuff.

**Comment by jmgasper** [comment]
Payment failed: [500]: Failed to get billing detail for the project.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment]
@afrisalyp - Sorry for the delay here.  I'm hoping to get the billing code fixed ASAP.

**Comment by afrisalyp** [comment]
No problem. Thanks.

**Comment by jmgasper** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30144220<br/><br/>```This is an automated message for ghostar via Topcoder X```
