### ISSUE TITLE
Failing Github access link

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#379]
The Github access link flow is failing.

Reported:

> A member is having trouble using the github link I sent him to join my repo. I had him try incognito and he got this
> In Topcoder-X, when generating the link, I selected member, not maintainer

![image-2](https://user-images.githubusercontent.com/21790/105949604-0a23b900-60c1-11eb-91b2-b22ae8539c84.png)

### Challenge testing

For this challenge you **MUST** fully test the Github flow.

### Challenge documentation

The security setup for groups is a bit weird on Github vs. Gitlab.  For this February 2021 challenge, please add a new `.md` file that describes how to set up a group and assign it to a repo, and then use that group with Topcoder-X to grant user permissions to a specific repo.

**Comment by jmgasper** [comment]
Logs from the production instance that may help:

```
error: Error happened in system
TypeError: Cannot read property 'count' of undefined
    at /topcoder-x-ui/src/common/db-helper.js:91:29
    at /topcoder-x-ui/node_modules/dynamoose/dist/Scan.js:267:24
    at _rejected (/topcoder-x-ui/node_modules/q/q.js:864:24)
    at /topcoder-x-ui/node_modules/q/q.js:890:30
    at Promise.when (/topcoder-x-ui/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/topcoder-x-ui/node_modules/q/q.js:808:41)
    at /topcoder-x-ui/node_modules/q/q.js:624:44
    at runSingle (/topcoder-x-ui/node_modules/q/q.js:137:13)
    at flush (/topcoder-x-ui/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
addUserToTeam called for 27107973-bfe9-4c78-bcbf-d978eadfce5e-1611848600826
addUserToTeam OwnerUserTeam undefined
adding b0a02f49fdacd08fbef0f80d439862aabe4fede0 to 4422530 with e219699ffd55d48abcdc8c4f6d1c066d7ffed283
error: DynamoDB scanOne error Error: Wait for Active timed out after 180000 ms.
error: Error happened in undefined
Error: Wait for Active timed out after 180000 ms.
    at Timeout.waitForActive [as _onTimeout] (/topcoder-x-ui/node_modules/dynamoose/dist/Table.js:198:36)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
error: Error happened in system
TypeError: Cannot read property 'count' of undefined
    at /topcoder-x-ui/src/common/db-helper.js:91:29
    at /topcoder-x-ui/node_modules/dynamoose/dist/Scan.js:267:24
    at _rejected (/topcoder-x-ui/node_modules/q/q.js:864:24)
    at /topcoder-x-ui/node_modules/q/q.js:890:30
    at Promise.when (/topcoder-x-ui/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/topcoder-x-ui/node_modules/q/q.js:808:41)
    at /topcoder-x-ui/node_modules/q/q.js:624:44
    at runSingle (/topcoder-x-ui/node_modules/q/q.js:137:13)
    at flush (/topcoder-x-ui/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error: Error happened in addGroupMember
ValidationError: [object Object] {
  "groupId": "8794607",
  "ownerUserToken": "fcd2bce189870826a22e0ef4f384dab0742b7be2134304ece5709faa3d341d0e",
  "normalUserToken": "52b556e135a4b5e53ccc5b23803c8351f8e08b50be63cff4058261229a1c56ae",
  "accessLevel" [1]: -- missing --
}

[1] "accessLevel" is required
    at Object.exports.process (/topcoder-x-ui/node_modules/joi/lib/errors.js:181:19)
    at internals.Object._validateWithOptions (/topcoder-x-ui/node_modules/joi/lib/types/any/index.js:651:31)
    at module.exports.internals.Any.root.validate (/topcoder-x-ui/node_modules/joi/lib/index.js:121:23)
    at module.exports.internals.Any.root.attempt (/topcoder-x-ui/node_modules/joi/lib/index.js:150:29)
    at Object.serviceMethodWithValidation (/topcoder-x-ui/src/common/helper.js:84:30)
    at Object.serviceMethodWithLogging [as addGroupMember] (/topcoder-x-ui/src/common/helper.js:59:37)
    at addUserToGroupCallback (/topcoder-x-ui/src/controllers/GitlabController.js:200:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
send request failed
```
