### ISSUE TITLE
Processing error

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#78]
Seen with the latest code, in the logs for the topcoder-x-processor installation.  Note that the challenge is not created or registered properly with the Github ticket:

```
2018-09-11T02:06:48.452756+00:00 app[worker.1]: error: Error happened in process
2018-09-11T02:06:48.452763+00:00 app[worker.1]: at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
2018-09-11T02:06:48.452765+00:00 app[worker.1]: at toError (/app/node_modules/mongodb/lib/utils.js:139:22)
2018-09-11T02:06:48.452761+00:00 app[worker.1]: MongoError: E11000 duplicate key error index: heroku_k366sw2n.issues.$challengeId_1 dup key: { : null }
2018-09-11T02:06:48.452767+00:00 app[worker.1]: at /app/node_modules/mongodb/lib/collection.js:668:23
2018-09-11T02:06:48.452769+00:00 app[worker.1]: at handleCallback (/app/node_modules/mongodb/lib/utils.js:120:56)
2018-09-11T02:06:48.452771+00:00 app[worker.1]: at /app/node_modules/mongodb/lib/bulk/unordered.js:465:9
2018-09-11T02:06:48.452772+00:00 app[worker.1]: at handleCallback (/app/node_modules/mongodb/lib/utils.js:120:56)
2018-09-11T02:06:48.452774+00:00 app[worker.1]: at resultHandler (/app/node_modules/mongodb/lib/bulk/unordered.js:413:5)
2018-09-11T02:06:48.452776+00:00 app[worker.1]: at /app/node_modules/mongodb-core/lib/connection/pool.js:469:18
2018-09-11T02:06:48.452777+00:00 app[worker.1]: at _combinedTickCallback (internal/process/next_tick.js:131:7)
2018-09-11T02:06:48.452779+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:180:9)
2018-09-11T02:06:48.455503+00:00 app[worker.1]: error:  message=E11000 duplicate key error index: heroku_k366sw2n.issues.$challengeId_1 dup key: { : null }, name=MongoError, stack=MongoError: E11000 duplicate key error index: heroku_k366sw2n.issues.$challengeId_1 dup key: { : null }
2018-09-11T02:06:48.455506+00:00 app[worker.1]: at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
2018-09-11T02:06:48.455508+00:00 app[worker.1]: at toError (/app/node_modules/mongodb/lib/utils.js:139:22)
2018-09-11T02:06:48.455511+00:00 app[worker.1]: at /app/node_modules/mongodb/lib/collection.js:668:23
2018-09-11T02:06:48.455513+00:00 app[worker.1]: at handleCallback (/app/node_modules/mongodb/lib/utils.js:120:56)
2018-09-11T02:06:48.455515+00:00 app[worker.1]: at /app/node_modules/mongodb/lib/bulk/unordered.js:465:9
2018-09-11T02:06:48.455517+00:00 app[worker.1]: at handleCallback (/app/node_modules/mongodb/lib/utils.js:120:56)
2018-09-11T02:06:48.455518+00:00 app[worker.1]: at resultHandler (/app/node_modules/mongodb/lib/bulk/unordered.js:413:5)
2018-09-11T02:06:48.455520+00:00 app[worker.1]: at /app/node_modules/mongodb-core/lib/connection/pool.js:469:18
2018-09-11T02:06:48.455522+00:00 app[worker.1]: at _combinedTickCallback (internal/process/next_tick.js:131:7)
2018-09-11T02:06:48.455526+00:00 app[worker.1]: return err.op;
2018-09-11T02:06:48.455524+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:180:9), driver=true, code=11000, index=0, errmsg=E11000 duplicate key error index: heroku_k366sw2n.issues.$challengeId_1 dup key: { : null }, getOperation=function () {
2018-09-11T02:06:48.455528+00:00 app[worker.1]: }, toJSON=function () {
2018-09-11T02:06:48.455530+00:00 app[worker.1]: return {code: err.code, index: err.index, errmsg: err.errmsg, op: err.op};
2018-09-11T02:06:48.455532+00:00 app[worker.1]: }, toString=function () {
2018-09-11T02:06:48.455534+00:00 app[worker.1]: return "WriteError(" + JSON.stringify(this.toJSON()) + ")";
2018-09-11T02:06:48.455536+00:00 app[worker.1]: }, logged=true**
```

**Comment by jmgasper** [comment]
Figured out the issue - new bug to fix.
